### ISSUE TITLE
Add support for Dvorak

### ISSUE THREAD

**Issue by pocc** [taylorconor/quinesnake#1]
`wasd` is QWERTY-specific, and doesn't work for other keyboards.

PR incoming for Dvorak's `,aoe`

**Comment by taylorconor** [comment]
The keybinding decision is arbitrary, I'm not going to switch from (fairly standard) wasd.

**Comment by pocc** [comment]
Agree that the keybinding is arbitrary. My PR includes a second file as most people use wasd.
