### ISSUE TITLE
Color doesn't work on my setup

### ISSUE THREAD

**Issue by haltman-at** [taylorconor/quinesnake#6]
For some reason the color isn't working on my setup -- characters are gray, the absence of a character is black.  You really have to hunt for that first food!  (After that subsequent ones can be found by looking for what changes.)

Anyway, my setup is:

OS: Release Linux Mint 18.3 Sylvia 64-bit
Terminal emulator: MATE Terminal 1.18.2
Shell: GNU bash, version 4.3.48(1)-release (x86_64-pc-linux-gnu)
g++: g++ (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
curses: 6.0+20160213-1ubuntu1 [I'm going by the pacakge manager here, I can't figure out how else to get my curses version; this is the version for the `libncurses5` package]

**Comment by cheesypeas** [comment]
Same issue here:

OS: Ubuntu Studio 16.04.5 LTS 64-bit
Terminal: xfce4-terminal 0.6.3
Shell: GNU bash, version 4.3.48(1)-release (x86_64-pc-linux-gnu)
g++: gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.11) 
curses: libncurses5-dev_6.0+20160213-1ubuntu1_amd64

HTH

**Comment by heyurw** [comment]
https://asciinema.org/a/243261

i'm solved this issue by changing `init_pair()` function from `init_pair(e,0,e+9)` to `init_pair(e,e,e + 2)`

**Comment by cheesypeas** [comment]
hmm just tried init_pair(e,e,e+2) and no difference for me at least.

**Comment by taylorconor** [comment]
Hi! Sorry for the delay. I added an extra note to the README in https://github.com/taylorconor/quinesnake/pull/9. Let me know if it works for you :)

**Comment by haltman-at** [comment]
Yup, that does it, thanks!
