### ISSUE TITLE
cheating quine?

### ISSUE THREAD

**Issue by jfmc** [taylorconor/quinesnake#7]
While impressive, I suspect that this is not real quine. It seems that the script is reading itself at the beginning and then, this would be a "cheating quine". See https://en.wikipedia.org/wiki/Quine_%28computing%29 for details. Perhaps it could be added to the README?

**Comment by taylorconor** [comment]
It's not a cheating quine.

The script does refer to itself (`$0`) in the beginning, but notice what it does:
```
/bin/ls>/dev/null;sed -n 's/.*.\/\*\(.*\)../\1/p' $0|I=$0 sh;exit;
echo g++ -std=c++11 -oo $I -lcurses -DI=int -DF=if -DK=return -includectime,curses.h,iostream,map,unistd.h|sed s/,/\ -include/g|sh;./o</dev/tty;exit
```

It doesn't read itself and is not concerned with the output of `$0`, it's just used so it can compile and run itself. The quine logic is all in the C++ part of the program, within the `LR"x(` string.

**Comment by jfmc** [comment]
Thanks for the explanation. It still think that it is worth adding those details (that the script part of the program reads itself but for a different purpose). I totally agree that the C++ part is quine.
